####################
# About zeromore   #
####################
# Zeromore initialization file, generally called config.ini, is responsible for
# configuring many of the aspects of Zeromore behavior.

	 
    name 		=	"zeromore server" 
    enable 		= 	true 
    status 		= 	"dev"
    version		=	"1.0"
    loglevel	=	"info"
    rpc_type	=	"go"  # string | flatbuffer 
    pack_type	=	"bufferio"
	
	[log]
		log_level	=	"info"
		log_behind_type = "console"  
		mongodb_host = "localhost"
		mongodb_port = "27017"
	
	[admin]
		http_port = "9090"
	    
    [connector]
    	websocket_port 	= 7898  
    	socket_port    	= 7002  
    	max_conections 	= 1024
    	max_packet_rate	= 100
    	max_conntions_ip= 100
      	max_packet_rate_unit = 10  
      	
    [object]
    	data_type 	= "redis"  #  Mysql| redis | monogo  
		redis_host 	= "127.0.0.1"
		redis_port 	= "6379"
		redis_password = ""
		monogo_host = "localhost"
		monogo_port = 3306
		mysql_host 	= "localhost"
		mysql_port 	= 3306
		mysql_password = ""
		    
	[worker]
        worker_language	= "php"  
        php_bin_path 	= "d:\\php7\\"
		worker_num 		= 2
		agent_host 		= "127.0.0.1"
		agent_port 		= 7102
		hub_host 		= "127.0.0.1"
		hub_port 		= 7302

	[worker_agent]
		host	=	"127.0.0.1" 
		port	=	"7102"
	 
	[hub] 
    	hub_host = "127.0.0.1" 
    	hub_port = "7302" 
 
	[area]
		init_area = ["area-global", "area-global2", "area-global3"]
		
		
		
      